name: Create or Update Release

on:
    workflow_dispatch:
    repository_dispatch:
        types: [publish-apk]

jobs:
    create-or-update-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout script in repo
              uses: actions/checkout@v3

            - name: Run publish-release
              uses: actions/github-script@v7
              id: gh-script
              env:
                  RELEASE_ID: ${{ github.event.client_payload.release_id }}
              with:
                  github-token: ${{ secrets.SOURCE_GH_TOKEN }}
                  result-encoding: string
                  script: |
                      const script = require('./publish-release.js')
                      await script({github, context, core})
